# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  errors:
    # TODOをProblemsに表示しない
    todo: ignore
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/generated_plugin_registrant.dart
    - test/**/*.mocks.dart
    - plugins/**
linter:
  rules:
    # 相対インポート
    prefer_relative_imports: true